### ISSUE TITLE
Enhancement: add support for passing through metadata, including EXIF orientation

### ISSUE THREAD

**Issue by 3xploiton3** [lovell/avif-cli#13]
https://sharp.pixelplumbing.com/changelog#v0313---21st-december-2022

**Comment by lovell** [comment]
Hello, the current semver range is wide enough to include the latest version, so you might need to update your lockfile e.g. via `npm upgrade` or similar.

https://github.com/lovell/avif-cli/blob/42f0dcc4ad5fcc963d28a8037c7873a91f6c0d86/package.json#L28

**Comment by lovell** [comment]
This input image is landscape and contains an EXIF Orientation that results in some software rotating it by 90 degrees clockwise.

I guess we'll need to either add a command line flag to rotate e.g. `--auto-orient`, or a flag to pass through all metadata (e.g. `--with-metadata`, which would use [. withMetadata()](https://sharp.pixelplumbing.com/api-output#withmetadata). I think the latter might be more useful as this will include XMP etc.

I'll label this as a future possible enhancement. Happy to accept a PR, if you're able.

**Comment by lovell** [comment]
The `--keep-metadata` flag, which takes advantage of the new [keepMetadata](https://sharp.pixelplumbing.com/api-output#keepmetadata) feature of sharp v0.33.0+, was added via commit https://github.com/lovell/avif-cli/commit/30e7c5f3e30a81541f0b0571b9439c485ae6982d and released in avif v0.5.2.
