### ISSUE TITLE
Wrong exit code, when no file was created

### ISSUE THREAD

**Issue by dgsiegel** [lovell/avif-cli#16]
I am running avif-cli like this: `avif --input='img/*.{jpg,jpeg,png}' --quality 64 --verbose`. This works fine, when at least one image will be converted. When all images already have been converted and `--overwrite` has not been set, avif will return with a status of `1` which will be interpreted as failure.

The culprit seems to be this line, which returns `undefined` in this case.

https://github.com/lovell/avif-cli/blob/main/lib/convert.js#L33

Changing it for example to `return true` would fix this issue.

**Comment by lovell** [comment]
Thanks for reporting, a PR with this fix would be most welcome, if you're able.

**Comment by dgsiegel** [comment]
> Thanks for reporting, a PR with this fix would be most welcome, if you're able.

Sure thing: https://github.com/lovell/avif-cli/pull/17

**Comment by lovell** [comment]
v0.5.1 now available with your fix, thank you.
