### ISSUE TITLE
Input directory should be default output directory

### ISSUE THREAD

**Issue by evayde** [lovell/avif-cli#7]
I think that the current implementation is pretty confusing. 

If we want the output-dir to be the same as input dir we have to provide an empty output-dir as a parameter, like: `avif --input="..." --output=""`

I guess that's confusing UX. It would be better when the default output-dir would be the input dir itself, especially when input dir is a glob pattern. 

I have opened a PR for it, https://github.com/lovell/avif-cli/pull/6

**Comment by lovell** [comment]
I agree, this makes sense, thank you for the suggestion and PR.

**Comment by lovell** [comment]
v0.1.0 now available with your change, thank you.
